name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Utiliser l'environnement Windows
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Utiliser la version de Python que tu veux

      # Si tu n'as pas de dépendances à installer, tu peux ignorer cette étape
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt  # Si tu n'as pas de requirements.txt, ignore cette ligne

      - name: Exécuter ton script Python
        run: |
          python title.py  # Remplace par le nom de ton script Python ou la commande que tu veux exécuter
