name: Python CI on Windows

# Trigger the workflow on push and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Use the latest version of Windows Server

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python (use the version that you require)
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # You can specify a specific version, like 3.8

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    # Step 4: Run the Python script that customizes the terminal title
    - name: Run title script
      run: |
        python title.py  # Adjust if your script is named differently

    # Step 5: Add any additional steps for testing or deployment (if needed)

    # Example: Running tests with pytest
    - name: Run tests with pytest
      run: |
        pip install pytest
        pytest  # Run the tests with pytest

    # Step 6: Optionally, open the File Explorer on the Windows runner
    - name: Open File Explorer (Windows only)
      run: |
        explorer %cd%
      shell: pwsh  # PowerShell shell

