name: TitleLibrary Tests

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:
  test:
    runs-on: windows-latest  # Use Windows-based runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python (make sure you use the correct version)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify the Python version you are using

      # Step 3: Run Pytest
      - name: Run Pytest tests
        run: |
          pytest  # Runs pytest to execute the tests
